- name: Snapshot Appliance Before Installing Product Support License
  isds:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isds.snapshots.create
    isdsapi:
      comment: "{{ install_license_comment }}"

- name: Import Product License
  isds:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action:     ibmsecurity.isds.license.install
    isdsapi:
      license : "{{ install_license_file }}"
  when: install_license_file is defined
  notify: Commit Changes

 # Commit license before doing anything else
- meta: flush_handlers
