- name: Configure NTP
  isds:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isds.date_time.set
    isdsapi:
      timeZone:   "{{ config_ntp_timeZone }}"
      ntpServers: "{{ config_ntp_ntp_servers }}"
  notify: Commit Changes
