- name: Get Firmware Level
  isds:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isds.firmware.get
  register: ret_obj

- name: Set variable for use by rest of playbook
  set_fact:
    firmware_ret_obj: "{{ ret_obj }}"
