- name: Set Host Records
  isds:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isds.host_records.set
    isdsapi:
      ip_addr:  "{{ item.addr }}"
      hostname: "{{ item.hostnames[0]['name'] }}"
  when: set_host_records is defined
  with_items: "{{ set_host_records }}"
  notify: Commit Changes

  # Commit all changes made until now
- meta: flush_handlers
